DELETE FROM cart_items;
DELETE FROM favorites;
DELETE FROM order_items;
DELETE FROM orders;
DELETE FROM products;
DELETE FROM categories;

INSERT INTO categories (slug, title) VALUES
  ('tshirts', 'Футболки'),
  ('hoodies', 'Худи и свитшоты'),
  ('outerwear', 'Верхняя одежда'),
  ('bottoms', 'Брюки'),
  ('footwear', 'Обувь'),
  ('headwear', 'Головные уборы'),
  ('accessories', 'Аксессуары'),
  ('souvenirs', 'Сувениры');

INSERT INTO products (
  id, category_slug, title, description, price_stars, photo_url,
  old_price_stars, sku, badge, stock_qty, is_active, search_text
) VALUES
  (1, 'tshirts', 'Belarus Ornament Core Tee', 'Премиальная футболка с переосмысленным белорусским орнаментом и фирменной маркировкой Nikitka AI.', 329, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/belarus-ornament-core-tee.png', 389, 'TEE-BY-001', 'Heritage', 12, 1, 'belarus ornament core tee футболка орнамент беларусь nikitka ai heritage'),
  (2, 'tshirts', 'Flag Motion Tee', 'Черная дизайнерская футболка с графикой на основе красно-зеленого кода Беларуси.', 339, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/flag-motion-tee.png', NULL, 'TEE-BY-002', 'Graphic', 9, 1, 'flag motion tee футболка черная красно зеленая графика беларусь nikitka ai'),
  (3, 'tshirts', 'Zubr Line Oversize Tee', 'Oversize-футболка с арт-графикой зубра и спокойной luxury-подачей.', 359, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/zubr-line-oversize-tee.png', 419, 'TEE-BY-003', 'Bison', 7, 1, 'zubr line oversize tee футболка зубр беларусь oversize nikitka ai'),
  (4, 'tshirts', 'Minimal Core Tee', 'Минималистичная базовая футболка с деликатным брендингом Nikitka AI.', 279, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/minimal-core-tee.png', NULL, 'TEE-BY-004', 'Core', 14, 1, 'minimal core tee белая базовая футболка nikitka ai core'),
  (5, 'hoodies', 'Minsk Grid Hoodie', 'Серый худи с графикой городской сетки Минска и рукавным флаговым акцентом.', 469, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/minsk-grid-hoodie.png', 529, 'HD-BY-001', 'City', 8, 1, 'minsk grid hoodie худи минск сетка город беларусь nikitka ai'),
  (6, 'hoodies', 'Castle Shadows Hoodie', 'Темный худи с силуэтами замков Мир и Несвиж в luxury night-обработке.', 499, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/castle-shadows-hoodie.png', 569, 'HD-BY-002', 'Castle', 6, 1, 'castle shadows hoodie худи замки мир несвиж беларусь nikitka ai'),
  (7, 'hoodies', 'Cornflower Code Crewneck', 'Свитшот с цифровым символом василька и контрастным брендингом.', 439, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/cornflower-code-crewneck.png', NULL, 'CR-BY-001', 'Cornflower', 10, 1, 'cornflower code crewneck свитшот василек беларусь nikitka ai'),
  (8, 'hoodies', 'Red Forest Signal Zip Hoodie', 'Zip-худи с лесным мотивом и красным сигнальным акцентом.', 489, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/red-forest-signal-zip-hoodie.png', 549, 'HD-BY-003', 'Forest', 7, 1, 'red forest signal zip hoodie худи молния лес беларусь nikitka ai'),
  (9, 'outerwear', 'Nesvizh Night Coach Jacket', 'Премиальная coach jacket с ночным архитектурным силуэтом Несвижа.', 619, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/nesvizh-night-coach-jacket.png', 699, 'OW-BY-001', 'Night', 5, 1, 'nesvizh night coach jacket куртка несвиж замок беларусь nikitka ai'),
  (10, 'outerwear', 'Polesie Mist Windbreaker', 'Легкая ветровка с туманной палитрой Полесья и красным акцентом.', 579, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/polesie-mist-windbreaker.png', NULL, 'OW-BY-002', 'Polesie', 6, 1, 'polesie mist windbreaker ветровка полесье беларусь nikitka ai'),
  (11, 'outerwear', 'Bison Winter Puffer Vest', 'Утепленный жилет с темно-зеленой палитрой и знаком зубра.', 649, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/bison-winter-puffer-vest.png', 739, 'OW-BY-003', 'Winter', 4, 1, 'bison winter puffer vest жилет зубр зима беларусь nikitka ai'),
  (12, 'bottoms', 'Border Rhythm Cargo Pants', 'Cargo-брюки с орнаментальным ритмом швов и функциональной luxury-конструкцией.', 529, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/border-rhythm-cargo-pants.png', 599, 'BT-BY-001', 'Utility', 6, 1, 'border rhythm cargo pants карго брюки орнамент беларусь nikitka ai'),
  (13, 'footwear', 'Zubr Trail Low', 'Дизайнерские trail-кроссовки в темно-зеленой гамме с акцентом силы зубра.', 719, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/zubr-trail-low.png', 799, 'FW-BY-001', 'Trail', 5, 1, 'zubr trail low кроссовки trail зубр обувь беларусь nikitka ai'),
  (14, 'footwear', 'State Code Chelsea Boot', 'Chelsea boots с глубоким зеленым верхом и государственным цветовым кодом.', 799, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/state-code-chelsea-boot.png', 899, 'FW-BY-002', 'Boots', 4, 1, 'state code chelsea boot челси ботинки беларусь красно зеленый nikitka ai'),
  (15, 'footwear', 'Ornament Derby', 'Премиальные derby с орнаментальным emboss-деталем и темно-красной строчкой.', 769, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/ornament-derby.png', NULL, 'FW-BY-003', 'Derby', 3, 1, 'ornament derby туфли дерби орнамент беларусь nikitka ai'),
  (16, 'footwear', 'Red Line Metro High-Top', 'Высокие кеды с графикой красной линии метро Минска.', 699, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/red-line-metro-high-top.png', 779, 'FW-BY-004', 'Metro', 5, 1, 'red line metro high top высокие кеды минск метро беларусь nikitka ai'),
  (17, 'footwear', 'Polesie Mist Hiker', 'Mid hiking boots с палитрой Полесья и premium outdoor-силуэтом.', 859, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/polesie-mist-hiker.png', 949, 'FW-BY-005', 'Hiker', 3, 1, 'polesie mist hiker hiking boots ботинки полесье беларусь nikitka ai'),
  (18, 'footwear', 'Castle Shadow Loafer', 'Лоферы с архитектурным emboss-мотивом и аристократичной подачей.', 739, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/castle-shadow-loafer.png', NULL, 'FW-BY-006', 'Loafer', 3, 1, 'castle shadow loafer лоферы замок беларусь nikitka ai'),
  (19, 'footwear', 'Forest Signal Mule', 'Дизайнерские mules с лесным кодом и контрастным боковым акцентом.', 629, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/forest-signal-mule.png', 699, 'FW-BY-007', 'Mule', 4, 1, 'forest signal mule мюли лес беларусь nikitka ai'),
  (20, 'footwear', 'Cornflower Tech Slip-On', 'Slip-on модель с цифровой floral-геометрией и premium tech-подошвой.', 669, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/cornflower-tech-slip-on.png', NULL, 'FW-BY-008', 'Slip-On', 4, 1, 'cornflower tech slip on слипоны василек беларусь nikitka ai'),
  (21, 'headwear', 'Bison Winter Ushanka', 'Современная премиальная ушанка с зимним характером Belarus Heritage.', 309, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/bison-winter-ushanka.png', 349, 'HW-BY-001', 'Winter', 5, 1, 'bison winter ushanka ушанка зима беларусь nikitka ai'),
  (22, 'headwear', 'State Line Trucker Luxe', 'Trucker cap с красно-зеленым кодом и контрастным брендингом.', 249, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/state-line-trucker-luxe.png', 289, 'HW-BY-002', 'Cap', 9, 1, 'state line trucker luxe кепка trucker беларусь nikitka ai'),
  (23, 'headwear', 'Zubr Wool Beanie', 'Шерстяная beanie с графикой зубра и флаговым боковым тегом.', 229, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/zubr-wool-beanie.png', NULL, 'HW-BY-003', 'Beanie', 9, 1, 'zubr wool beanie шапка beanie зубр беларусь nikitka ai'),
  (24, 'headwear', 'Cornflower Code Beanie', 'Фактурная beanie с васильковым символом и читаемым логотипом.', 239, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/cornflower-code-beanie.png', 279, 'HW-BY-004', 'Knit', 8, 1, 'cornflower code beanie шапка василек беларусь nikitka ai'),
  (25, 'headwear', 'Heritage Knit Beanie', 'Трикотажная beanie с орнаментальным кодом Belarus Heritage.', 239, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/heritage-knit-beanie.png', NULL, 'HW-BY-005', 'Heritage', 8, 1, 'heritage knit beanie шапка орнамент беларусь nikitka ai'),
  (26, 'headwear', 'Forest Signal Balaclava', 'Премиальная балаклава с forest signal графикой и luxury knit-текстурой.', 269, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/forest-signal-balaclava.png', 319, 'HW-BY-006', 'Balaclava', 5, 1, 'forest signal balaclava балаклава лес беларусь nikitka ai'),
  (27, 'accessories', 'State Code Passport Holder', 'Кожаный чехол для паспорта в темно-зеленой гамме с красным фиксатором.', 299, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/state-code-passport-holder.jpeg', 349, 'AC-BY-001', 'Travel', 7, 1, 'state code passport holder чехол паспорт беларусь nikitka ai'),
  (28, 'souvenirs', 'Mir & Nesvizh Art Poster', 'Коллекционный интерьерный постер с графикой Мирского и Несвижского замков.', 219, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/mir-nesvizh-art-poster.jpeg', NULL, 'SV-BY-001', 'Poster', 5, 1, 'mir nesvizh art poster постер замки беларусь nikitka ai'),
  (29, 'souvenirs', 'Belarus Heritage Gallery Poster', 'Второй постер серии Belarus Heritage с коллажной галерейной подачей.', 219, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/belarus-heritage-gallery-poster-v2.jpeg', NULL, 'SV-BY-002', 'Gallery', 5, 1, 'belarus heritage gallery poster постер беларусь nikitka ai gallery collage'),
  (30, 'souvenirs', 'Belarus Grid Mug', 'Керамическая кружка с орнаментальным поясом и линиями минской архитектуры.', 169, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/belarus-grid-mug.jpeg', 199, 'SV-BY-003', 'Home', 12, 1, 'belarus grid mug кружка орнамент минск беларусь nikitka ai'),
  (31, 'souvenirs', 'Belarus Forest Candle', 'Ароматическая свеча в темном стекле с лесной этикеткой Belarus.', 189, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/belarus-forest-candle.jpeg', NULL, 'SV-BY-004', 'Candle', 10, 1, 'belarus forest candle свеча лес беларусь nikitka ai'),
  (32, 'souvenirs', 'Belarus Pattern Coasters', 'Набор подставок с разными белорусскими графическими паттернами.', 159, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/belarus-pattern-coasters.jpeg', NULL, 'SV-BY-005', 'Set', 9, 1, 'belarus pattern coasters подставки орнамент беларусь nikitka ai'),
  (33, 'souvenirs', 'Belarus Expedition Thermos', 'Металлический термос с forest-river графикой и красным акцентом.', 209, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/belarus-expedition-thermos.jpeg', 249, 'SV-BY-006', 'Travel', 8, 1, 'belarus expedition thermos термос беларусь nikitka ai'),
  (34, 'souvenirs', 'Zubr Form Desk Sculpture', 'Настольная скульптура, вдохновленная формой зубра и белорусской пластикой.', 399, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/zubr-form-desk-sculpture.jpeg', NULL, 'SV-BY-007', 'Art', 3, 1, 'zubr form desk sculpture скульптура зубр беларусь nikitka ai'),
  (35, 'souvenirs', 'Belarus Heritage Gift Box', 'Подарочный бокс с curated-набором объектов Belarus Heritage.', 359, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/belarus-heritage-gift-box.jpeg', 419, 'SV-BY-008', 'Gift', 4, 1, 'belarus heritage gift box подарок беларусь nikitka ai'),
  (36, 'souvenirs', 'Polesie Mist Notebook', 'Премиальный блокнот с Polesie-эстетикой, тиснением и quiet luxury-палитрой.', 149, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/polesie-mist-notebook.jpeg', NULL, 'SV-BY-009', 'Stationery', 11, 1, 'polesie mist notebook блокнот беларусь nikitka ai'),
  (37, 'souvenirs', 'Zubr Metal Magnet', 'Коллекционный металлический магнит с графикой зубра.', 129, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/zubr-metal-magnet.jpeg', NULL, 'SV-BY-010', 'Magnet', 14, 1, 'zubr metal magnet магнит зубр беларусь nikitka ai'),
  (38, 'souvenirs', 'Belarus Winter Snow Globe', 'Дизайнерский снежный шар с зимним пейзажем Беларуси.', 249, 'https://flat-brook-a0f7.zimoaiart.workers.dev/products/belarus-winter-snow-globe.jpeg', 299, 'SV-BY-011', 'Winter', 6, 1, 'belarus winter snow globe снежный шар беларусь nikitka ai');
